-- ====================================================================
-- BUTUAN CITY COMPLAINTS MANAGEMENT SYSTEM
-- Seed Data: 86 Official Barangays, Categories, & Initial Records
-- ====================================================================

-- 1. SEED 86 OFFICIAL BUTUAN CITY BARANGAYS
INSERT INTO public.barangays (name, status) VALUES
('Agao Pob. (Barangay 9)', 'ACTIVE'),
('Agusan Pequeño', 'ACTIVE'),
('Alviola Village', 'ACTIVE'),
('Ambago', 'ACTIVE'),
('Amparo', 'ACTIVE'),
('Ampayon', 'ACTIVE'),
('Anticala', 'ACTIVE'),
('Antongalon', 'ACTIVE'),
('Aupagan', 'ACTIVE'),
('Baan KM 3', 'ACTIVE'),
('Baan Riverside', 'ACTIVE'),
('Babag', 'ACTIVE'),
('Bading Pob. (Barangay 22)', 'ACTIVE'),
('Bancasi', 'ACTIVE'),
('Banza', 'ACTIVE'),
('Baobaoan', 'ACTIVE'),
('Basag', 'ACTIVE'),
('Bayanihan Pob. (Barangay 27)', 'ACTIVE'),
('Bilay', 'ACTIVE'),
('Bit-os', 'ACTIVE'),
('Bitan-agan', 'ACTIVE'),
('Bobon', 'ACTIVE'),
('Bonbon', 'ACTIVE'),
('Bugabus', 'ACTIVE'),
('Cabcabon', 'ACTIVE'),
('Camayahan', 'ACTIVE'),
('Dagohoy Pob. (Barangay 7)', 'ACTIVE'),
('Dankias', 'ACTIVE'),
('De Oro', 'ACTIVE'),
('Diego Silang Pob. (Barangay 6)', 'ACTIVE'),
('Doongan', 'ACTIVE'),
('Dulag', 'ACTIVE'),
('Dumalagan', 'ACTIVE'),
('Florida', 'ACTIVE'),
('Golden Ribbon Pob. (Barangay 2)', 'ACTIVE'),
('Holy Redeemer Pob. (Barangay 23)', 'ACTIVE'),
('Humabon Pob. (Barangay 11)', 'ACTIVE'),
('Imadejas Pob. (Barangay 24)', 'ACTIVE'),
('Kinamlutan', 'ACTIVE'),
('Lapu-lapu Pob. (Barangay 8)', 'ACTIVE'),
('Lemon', 'ACTIVE'),
('Leon Kilat Pob. (Barangay 13)', 'ACTIVE'),
('Libertad', 'ACTIVE'),
('Limaha Pob. (Barangay 14)', 'ACTIVE'),
('Los Angeles', 'ACTIVE'),
('Lumbocan', 'ACTIVE'),
('Maguinda', 'ACTIVE'),
('Mahay', 'ACTIVE'),
('Mahogany Pob. (Barangay 21)', 'ACTIVE'),
('Maibu', 'ACTIVE'),
('Mandamo', 'ACTIVE'),
('Manila de Bugabus', 'ACTIVE'),
('Maon Pob. (Barangay 1)', 'ACTIVE'),
('Masao', 'ACTIVE'),
('Maug', 'ACTIVE'),
('New Society Village Pob. (Barangay 26)', 'ACTIVE'),
('Nongnong', 'ACTIVE'),
('Obrero Pob. (Barangay 18)', 'ACTIVE'),
('Ong Yiu Pob. (Barangay 16)', 'ACTIVE'),
('Pagatpatan', 'ACTIVE'),
('Pangabugan', 'ACTIVE'),
('Pianing', 'ACTIVE'),
('Pigdaulan', 'ACTIVE'),
('Pinamanculan', 'ACTIVE'),
('Port Poyohon Pob. (Barangay 17)', 'ACTIVE'),
('Rajah Soliman Pob. (Barangay 4)', 'ACTIVE'),
('Salvacion', 'ACTIVE'),
('San Ignacio Pob. (Barangay 15)', 'ACTIVE'),
('San Mateo', 'ACTIVE'),
('San Vicente', 'ACTIVE'),
('Santa Ines', 'ACTIVE'),
('Santo Niño', 'ACTIVE'),
('Sikatuna Pob. (Barangay 10)', 'ACTIVE'),
('Silongan Pob. (Barangay 5)', 'ACTIVE'),
('Sumilihon', 'ACTIVE'),
('Tagabaca', 'ACTIVE'),
('Taguibo', 'ACTIVE'),
('Taligaman', 'ACTIVE'),
('Tandag Pob. (Barangay 19)', 'ACTIVE'),
('Tiniwisan', 'ACTIVE'),
('Tungao', 'ACTIVE'),
('Urduja Pob. (Barangay 3)', 'ACTIVE'),
('Victoria Pob. (Barangay 20)', 'ACTIVE'),
('Villa Kananga', 'ACTIVE')
ON CONFLICT (name) DO NOTHING;

-- 2. SEED DEFAULT COMPLAINT CATEGORIES
INSERT INTO public.complaint_categories (name, description, status) VALUES
('Garbage / Improper Waste Disposal', 'Uncollected refuse, illegal dumping, littering, and dirty surroundings.', 'ACTIVE'),
('Flooding', 'Overflowing rainwater, riverbank swelling, and submerged roads.', 'ACTIVE'),
('Road Damage', 'Potholes, unpaved surfaces, cracks, and hazardous road conditions.', 'ACTIVE'),
('Drainage Problem', 'Clogged culverts, open manholes, canal blockages, and foul odor.', 'ACTIVE'),
('Streetlight Problem', 'Broken, unlit, blinking, or fallen street lamp posts.', 'ACTIVE'),
('Traffic Concern', 'Illegal parking, obstructed lanes, malfunctioning traffic lights.', 'ACTIVE'),
('Environmental Concern', 'Smoke belching, river pollution, illegal cutting of trees, chemical smells.', 'ACTIVE'),
('Public Facility Problem', 'Damaged barangay hall, public park fixtures, sports complex facilities.', 'ACTIVE'),
('Water Supply Problem', 'Broken water pipes, low water pressure, contaminated supply.', 'ACTIVE'),
('Noise Complaint', 'Excessive videoke after curfew, loud modified mufflers, disturbance.', 'ACTIVE'),
('Other', 'General community concerns and other public service requests.', 'ACTIVE')
ON CONFLICT (name) DO NOTHING;
